services:
  - type: web
    name: gesture-frontend
    env: static
    plan: free
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://jsonplaceholder.typicode.com
