services:
  # PostgreSQL 데이터베이스
  - type: pserv
    name: gesture-postgres
    plan: free
    databaseName: gesture
    user: postgres

  # Spring Boot 백엔드 API (Docker)
  - type: web
    name: gesture-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: gesture-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: "https://gesture-frontend.onrender.com"
      - key: PORT
        value: 8080

  # Vue.js 프론트엔드 (정적 사이트)
  - type: web
    name: gesture-frontend
    env: static
    plan: free
    buildCommand: "npm ci && npm run build"
    staticPublishPath: ./dist
    buildDir: ./frontend
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://gesture-backend.onrender.com/api"
      - key: NODE_VERSION
        value: "18"
