spring:
  application:
    name: gesture-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/gesture
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    com.gesture.backend: DEBUG
    org.springframework.security: DEBUG

# JWT Configuration
jwt:
  secret: dev-secret-key-for-testing-only
  expiration: 86400000
  refresh-expiration: 604800000

# CORS Configuration  
cors:
  allowed-origins: http://localhost:5173,http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
